import { Injectable } from '@nestjs/common';
import { UserEntity } from 'src/entities/user.entity';
import { decryptNumber, decryptString } from 'src/security/aes/encrypt.util';

interface ContractData {
  contractId: string | undefined;
  status: string | undefined;
  amount: number | undefined;
  confirmedAt: Date | undefined;
  plataform: string | undefined;
  taxAmount: number | undefined;
  transcationsIds: string[] | undefined;
}

@Injectable()
export class PdfSectionBuilderService {
  /**
   * Constrói o header do PDF
   */
  buildHeader(
    pdf: PDFKit.PDFDocument,
    contract: ContractData,
    version: number,
  ): void {
    pdf
      .fontSize(18)
      .font('Helvetica-Bold')
      .text('AFFILIATE OVERVIEW & FINANCIAL SUMMARY', { align: 'center' });

    pdf.moveDown(0.5);

    pdf
      .fontSize(9)
      .font('Helvetica')
      .text(`Reference ID: ${contract.contractId} | Version: ${version}`, {
        align: 'center',
      });

    pdf
      .fontSize(8)
      .font('Helvetica-Oblique')
      .text(`Generated at: ${new Date().toISOString()} (UTC)`, {
        align: 'center',
      });

    pdf.moveDown(1);
    pdf.moveTo(50, pdf.y).lineTo(545, pdf.y).stroke();
    pdf.moveDown(1);
  }

  /**
   * Constrói a seção de aviso importante
   */
  buildNotice(pdf: PDFKit.PDFDocument): void {
    pdf.fontSize(10).font('Helvetica-Bold').text('IMPORTANT NOTICE');

    pdf
      .fontSize(8)
      .font('Helvetica')
      .text(
        'This document is a visual, informational representation generated by the platform.',
        { indent: 20 },
      );

    pdf.text(
      'It does not constitute a contract, invoice, or legal obligation of any kind.',
      { indent: 20 },
    );

    pdf.moveDown(1);
  }

  /**
   * Constrói a seção de informações gerais do contrato
   */
  buildOverviewInfo(
    pdf: PDFKit.PDFDocument,
    contract: ContractData,
    version: number,
  ): void {
    pdf.fontSize(11).font('Helvetica-Bold').text('OVERVIEW INFORMATION');

    const items = [
      ['Reference ID', contract.contractId],
      ['Version', version.toString()],
      ['Total Amount', `$${contract.amount?.toFixed(2)}`],
      ['Status', contract.status?.toUpperCase()],
      ['Currency', 'USD'],
    ];

    items.forEach(([label, value]) => {
      if (!value) return;

      pdf.fontSize(9).font('Helvetica-Bold').text(`${label}:`, { indent: 20 });
      pdf.fontSize(9).font('Helvetica').text(value, { indent: 40 });
    });

    pdf.moveDown(1);
  }

  /**
   * Constrói a seção de informações do afiliado
   */
  buildAffiliateInfo(pdf: PDFKit.PDFDocument, user: UserEntity): void {
    pdf.fontSize(11).font('Helvetica-Bold').text('AFFILIATE INFORMATION');

    const items = [
      ['User ID', user.userId],
      ['Affiliate Code', user.affiliateCode],
      ['Account Status', user.status.toUpperCase()],
    ];

    items.forEach(([label, value]) => {
      pdf.fontSize(9).font('Helvetica-Bold').text(`${label}:`, { indent: 20 });
      pdf.fontSize(9).font('Helvetica').text(value, { indent: 40 });
    });

    pdf.moveDown(1);
  }

  /**
   * Constrói a seção de transações relacionadas
   */
  async buildTransactions(
    pdf: PDFKit.PDFDocument,
    contract: ContractData,
    user: UserEntity,
  ): Promise<void> {
    if (!contract.transcationsIds?.length) return;

    pdf.fontSize(11).font('Helvetica-Bold').text('RELATED TRANSACTIONS');

    for (let i = 0; i < Math.min(contract.transcationsIds.length, 10); i++) {
      const txId = contract.transcationsIds[i];
      const tx = user.affiliateds
        .flatMap((a) => a.transactions)
        .find((t) => t.id === txId);

      if (tx) {
        const amount = await decryptNumber(tx.amount);
        const productName = await decryptString(tx.productName);

        pdf
          .fontSize(9)
          .font('Helvetica')
          .text(`${i + 1}. $${amount} | ${productName}`, {
            indent: 20,
          });
      }
    }

    pdf.moveDown(1);
  }

  /**
   * Constrói a seção de observações gerais
   */
  buildObservations(pdf: PDFKit.PDFDocument): void {
    pdf.fontSize(11).font('Helvetica-Bold').text('GENERAL OBSERVATIONS');

    pdf
      .fontSize(8)
      .font('Helvetica')
      .text(
        `This document reflects platform data at the time of generation.
Any modification invalidates the digital signature and integrity hashes.`,
        {
          indent: 20,
          width: 445,
          align: 'justify',
        },
      );

    pdf.moveDown(1);
  }

  /**
   * Constrói a marca d'água invisível
   */
  buildInvisibleWatermark(
    pdf: PDFKit.PDFDocument,
    contract: ContractData,
    user: UserEntity,
  ): void {
    pdf.opacity(0.01);
    pdf
      .fontSize(50)
      .rotate(-45, { origin: [300, 400] })
      .text(
        `REF:${contract.contractId} | CONTRACT FOR:${user.affiliateCode}`,
        100,
        300,
        { align: 'center' },
      );
    pdf.rotate(45, { origin: [300, 400] });
    pdf.opacity(1);
  }

  /**
   * Constrói a seção de registro de integridade
   */
  buildIntegritySection(pdf: PDFKit.PDFDocument, integrityHash: string): void {
    pdf.moveTo(50, pdf.y).lineTo(545, pdf.y).stroke();
    pdf.moveDown(0.5);

    pdf
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('DOCUMENT INTEGRITY RECORD', { align: 'center' });

    pdf.moveDown(0.3);

    pdf
      .fontSize(7)
      .font('Helvetica-Oblique')
      .text(`Integrity Hash (SHA3-256):\n${integrityHash}`, {
        align: 'center',
        width: 495,
      });
  }
}
